### ISSUE TITLE
List Index out of range, Error 2000

### ISSUE THREAD

**Issue by ghost** [ukdtom/ExportTools.bundle#121]
Hello

I get the following error

<Response code="2000" status="IndexError: list index out of range">
<Traceback>
Traceback (most recent call last): File "/usr/lib/plexmediaserver/Resources/Plug-ins-77cb9455c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 70, in launch playlist=playlist) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/output.py", line 69, in getOutFileName './/Directory[@title="' + title + '"]')[0] File "/usr/lib/plexmediaserver/Resources/Plug-ins-77cb9455c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda> _getitem_ = lambda x, y: x.__getitem__(y), IndexError: list index out of range
</Traceback>
</Response>

Thanks

**Comment by ukdtom** [comment]
A zip of all ExportTools logs please, right after reproducing

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of response
