### ISSUE TITLE
URL Launch without level

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/ExportTools.bundle#136]
Cause an exception like:

2020-05-25 04:10:14,996 (50f8) :  CRITICAL (logkit:25) - Newtitle is Movies
2020-05-25 04:10:14,996 (50f8) :  CRITICAL (logkit:25) - Level is None
2020-05-25 04:10:14,996 (50f8) :  CRITICAL (logkit:25) - timestr is 
2020-05-25 04:10:14,996 (50f8) :  CRITICAL (core:574) - Exception handling due to cannot concatenate 'str' and 'NoneType' objects (most recent call last):
  File "C:\Users\admin\AppData\Local\Plex Media Server\Plug-ins\ExportTools.bundle\Contents\Code\output.py", line 84, in getOutFileName
    newtitle + '-' + level + timestr + extension)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by mescon** [comment]
For me, the library list never populates whatever I do.
I tried using the direct URL method, but got served with this XML response:

```
<Response code="2000" status="TypeError: cannot concatenate 'str' and 'NoneType' objects">
<Traceback>
Traceback (most recent call last): File "/usr/lib/plexmediaserver/Resources/Plug-ins-219a9974e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 70, in launch playlist=playlist) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/output.py", line 78, in getOutFileName newtitle + '-' + level + timestr + extension) TypeError: cannot concatenate 'str' and 'NoneType' objects
</Traceback>
</Response>
```
On the system I have python 2.7.17 as well as python 3.6.9.
The plugin folder is owned by the same user as the Plex Server is running as of course.

**Comment by ukdtom** [comment]
I can't use above to anything!

I need a zip of logs from ET

**Comment by ukdtom** [comment]
Closed due to lack of response
