### ISSUE TITLE
Traceback Error 

### ISSUE THREAD

**Issue by ghost** [ukdtom/ExportTools.bundle#138]
Hello, I get this error, attached logs this time, regards

Traceback (most recent call last): File "/usr/lib/plexmediaserver/Resources/Plug-ins-add6f438d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 70, in launch playlist=playlist) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/output.py", line 74, in getOutFileName newtitle + '-' + level + timestr + extension) TypeError: cannot concatenate 'str' and 'NoneType' objects

[com.plexapp.plugins.ExportTools.log](https://github.com/ukdtom/ExportTools.bundle/files/4741915/com.plexapp.plugins.ExportTools.log)

**Comment by ukdtom** [comment]
Permission problem

From the log:
`IOError: [Errno 13] Permission denied: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/DefaultPrefs.json'`

The user that runs PMS must have full rights to that file

**Comment by ghost** [comment]
So I corrected permissions. Still get 

Traceback (most recent call last): File "/usr/lib/plexmediaserver/Resources/Plug-ins-add6f438d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 70, in launch playlist=playlist) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/output.py", line 74, in getOutFileName newtitle + '-' + level + timestr + extension) TypeError: cannot concatenate 'str' and 'NoneType' objects

[com.plexapp.plugins.ExportTools.log](https://github.com/ukdtom/ExportTools.bundle/files/4742130/com.plexapp.plugins.ExportTools.log)

**Comment by ukdtom** [comment]
Please try this one.
It's not a fix, but contains additional logging

https://github.com/ukdtom/ExportTools.bundle/archive/tommy-work.zip

**Comment by ghost** [comment]
Thanks

It displays this error: I was asked via url to scan section: "Films" with skip timestamp set to "False" and with a level of "None". PlayList is set to False. Output file is: "None"

I have set movies to level 5 and output as csv in GUI. In GUI in settings it does not load the sources list even on reload and refresh

Ive no idea why it's trying to write to screeners. I have not specified that anywhere 


[com.plexapp.plugins.ExportTools-3.log](https://github.com/ukdtom/ExportTools.bundle/files/4742364/com.plexapp.plugins.ExportTools-3.log)

**Comment by ukdtom** [comment]
You have NOT defined a correct output path, where the plugin can write to
`2020-06-07 15:42:36,737 (7fc9aaffd700) :  INFO (__init__:1430) - Setting Export_Path set to: None
2020-06-07 15:42:36,737 (7fc9aaffd700) :  INFO (__init__:1430) - Setting Auto_Path set to: True`

See: https://github.com/ukdtom/ExportTools.bundle/wiki/Configuration#export-path


Nor have you given your plex user correct rights to the plugin folder, even though you said you did!

`2020-06-07 15:42:27,796 (7fc9abfff700) :  DEBUG (__init__:192) - Exception handling due to [Errno 13] Permission denied: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/DefaultPrefs.json'`

**Comment by ghost** [comment]
Hello, 

I got it working but it wants to write to a directory I didn't specify

Thanks

**Comment by ukdtom** [comment]
The Wiki I linked towards specify, that you should enter a path, as well as untick "AutoPath"

**Comment by ghost** [comment]
Thanks for all your help. A wonderful tool
